spring:
  application:
    name: service-items
server:
  port: 8002

#Si los puertos son dinamicos esto se debe comentar 
service-products:
  ribbon:
    listOfServers: localhost:8001,localhost:9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      